# Generated by Django 5.2.5 on 2025-09-05 13:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_total_project_cap_alter_comment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='total_donations',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
