# Generated by Django 5.2.5 on 2025-09-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_managers_account_birthdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='country',
            field=models.CharField(blank=True, choices=[('EG', 'Egypt'), ('US', 'United States'), ('UK', 'United Kingdom')], null=True),
        ),
    ]
